spring.application.name=03-Actuator

# Cấu hình cho phép truy xuất các thành phần (tất cả các thành phần *)
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
# Cấu hình info
info.app.name=My Application
info.app.description=This is my application
info.app.version=1.0.0
info.Exercise=Learn how to use Dependency Actuator